/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab2;

import lab2.functions.Func;
import lab2.functions.FunctionsSystem;
import lab2.functions.basic.Ln;
import lab2.functions.basic.Sin;
import lab2.functions.logariphmic.Log10;
import lab2.functions.logariphmic.Log2;
import lab2.functions.trigonometric.*;
import lab2.utils.CsvUtils;
import org.checkerframework.checker.units.qual.C;

import java.io.FileNotFoundException;

public class App {
    public static void main(String[] args) {
        Func function = new FunctionsSystem();

        try {
            CsvUtils csvUtils = new CsvUtils(String.format("csv/%s.csv",
                    function.getClass().getSimpleName()),
                    function, -3.14, 3.14, 0.01, 0.01);
            csvUtils.writeCsv();
        } catch (FileNotFoundException e) {
            System.out.println("File not found");
        }
    }
}
