/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab2;

import lab2.utils.CsvUtils;

import java.io.FileNotFoundException;

public class App {

    public static void main(String[] args) throws FileNotFoundException {

        CsvUtils csvUtils = new CsvUtils("cos.csv", "cos", -5, 5, 1, 0.1);
        csvUtils.writeCsv();
    }
}

